power = 23 # min 5dBm max 23dBm
hasPa = True # has a power amplifier (adds 6dBm)
callsign = "ON3URE-21"
#symbol = '/b' # bike
#symbol = '/>' # car
#symbol = '\>' # car
symbol = 'S>' # lora car
#symbol = 'Uk' # truck
#symbol = '/j' # jeep
#symbol = '/v' # truck
#symbol = '/u' # 18 wheeler
#symbol = '/U' # bus
comment = "https://RF.Guru"
rate = 10 # seconds (packet frequency when moving)
keepalive = 10 # in seconds (When no movement report every ...) when on solar/battary set this 900 (15 mins)
distance = 100 # minimum distance change to report
voltage = True # to measure voltage of the connected battery
i2cEnabled = False
i2cDevices = ["BME680"]
bme680_tempOffset = 0
