power = 23 # min 5 max 23 (the 1W PA version is not configurable, always maximum)
pa = True # has a power amplifier
callsign = "ON3URE-11"
#symbol = '/b' # bike
#symbol = '/>' # car
#symbol = '\>' # car
symbol = 'L>' # lora car
#symbol = '/k' # truck
#symbol = '/j' # jeep
#symbol = '/v' # truck
#symbol = '/u' # 18 wheeler
#symbol = '/U' # bus
comment = "https://RF.Guru"
rate = 6 # seconds (packet frequency when moving)
keepalive = 30 # in seconds (When no movement report every ...) when on solar/battary set this 900 (15 mins)
distance = 5 # minimum distance change to report
voltage = False # to measure voltage of the connected battery
