power = 23 # min 5dBm max 23dBm
pa = False # has a power amplifier (adds 6dBm)
callsign = "ON3URE-1"
#symbol = '/b' # bike
#symbol = '/>' # car
#symbol = '\>' # car
symbol = 'U>' # lora car
#symbol = '/k' # truck
#symbol = '/j' # jeep
#symbol = '/v' # truck
#symbol = '/u' # 18 wheeler
#symbol = '/U' # bus
comment = "https://RF.Guru"
rate = 10 # seconds (packet frequency when moving)
keepalive = 900 # in seconds (When no movement report every ...) when on solar/battary set this 900 (15 mins)
distance = 100 # minimum distance change to report
voltage = True # to measure voltage of the connected battery
i2c = ["SHTC3"]
