; PlatformIO Project Configuration File
;
; RF.Guru LoRa 433 APRS Tracker
; RP2040 with USB Mass Storage for config

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem = fatfs
board_build.arduino.earlephilhower.usb_manufacturer = RF.Guru
board_build.arduino.earlephilhower.usb_product = LoRa433APRSTracker
board_build.arduino.earlephilhower.usb_vid = 0x1209
board_build.arduino.earlephilhower.usb_pid = 0xFF42
board_build.filesystem_size = 0.5m
monitor_speed = 115200
monitor_raw = yes
lib_deps =
    sandeepmistry/LoRa
    mikalhart/TinyGPSPlus
    adafruit/Adafruit BME680 Library
    adafruit/Adafruit SHTC3 Library
